[theme]

# Primary accent for interactive elements
primaryColor = '#175cff'

# Background color for the main content area
backgroundColor = '#ffffff'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#f3f5f7'

# Color used for almost all text
textColor = '#021528'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"